import { afterEach, describe, expect, test, vi } from 'vitest'
import { type Attachment, WsAttachmentBinding } from '../src/ws-attachment-binding'
const commit = (o: WsAttachmentBinding, b: Attachment) => o.snapshotApplied(b.clientId, b)
const begin = (o: WsAttachmentBinding, c: string, r = c, t = 'target') => o.beginAttach(c, r, t)
const expectViolation = (owner: WsAttachmentBinding, binding: Attachment) =>
	expect(owner.snapshotApplied(binding.clientId, binding)).toEqual({
		ok: false,
		reason: 'protocol-violation',
	})
describe('WsAttachmentBinding', () => {
	afterEach(() => vi.useRealTimers())
	test('locks input until the matching snapshot commits', () => {
		const owner = new WsAttachmentBinding()
		const binding = owner.beginAttach('a', 'request-a', 'target-a')
		expect(owner.acceptsInput('a')).toBe(false)
		expect(commit(owner, binding).ok).toBe(true)
		expect(owner.acceptsInput('a')).toBe(true)
	})
	test('times out B without restoring committed A', () => {
		vi.useFakeTimers()
		const expired: Attachment[] = []
		const owner = new WsAttachmentBinding({ onTimeout: (binding) => expired.push(binding) })
		const a = begin(owner, 'client', 'a', 'target-a')
		commit(owner, a)
		const b = begin(owner, 'client', 'b', 'target-b')
		vi.advanceTimersByTime(9_999)
		expect(owner.getCapability('client', b.attachmentId)).not.toBeNull()
		vi.advanceTimersByTime(1)
		expect(owner.getCapability('client', b.attachmentId)).toBeNull()
		expect(owner.getCapability('client', a.attachmentId)).toMatchObject({ committed: true })
		expect(owner.acceptsInput('client')).toBe(false)
		expect(expired).toEqual([b])
		vi.advanceTimersByTime(10_000)
		expect(expired).toHaveLength(1)
	})
	test('supersedes B, rejects its late ack, and commits C', () => {
		const owner = new WsAttachmentBinding()
		const a = begin(owner, 'client', 'a')
		commit(owner, a)
		const b = begin(owner, 'client', 'b')
		const c = begin(owner, 'client', 'c')
		expect(owner.isCurrentAttempt('client', b)).toBe(false)
		expectViolation(owner, b)
		expect(commit(owner, c).ok).toBe(true)
		expect(owner.getCapability('client', a.attachmentId)).toBeNull()
		expect(owner.acceptsInput('client')).toBe(true)
	})
	test('releases committed and provisional capabilities on repeated disconnect/dispose', () => {
		vi.useFakeTimers()
		const owner = new WsAttachmentBinding()
		const a = begin(owner, 'client', 'a')
		commit(owner, a)
		const b = begin(owner, 'client', 'b')
		owner.disconnect('client')
		owner.dispose('client')
		owner.disconnect('client')
		expect(owner.getCapability('client', a.attachmentId)).toBeNull()
		expect(owner.getCapability('client', b.attachmentId)).toBeNull()
		expect(vi.getTimerCount()).toBe(0)
	})
	test('keeps IDs global and rejects collision without retry or interchange', () => {
		const owner = new WsAttachmentBinding()
		const a = begin(owner, 'a')
		const b = begin(owner, 'b')
		expect(a.attachmentId).not.toBe(b.attachmentId)
		expect(owner.getCapability('b', a.attachmentId)).toBeNull()
		const id = vi.fn(() => 'same-id')
		const collisionOwner = new WsAttachmentBinding({ idGenerator: id })
		begin(collisionOwner, 'a')
		expect(() => begin(collisionOwner, 'b')).toThrow('collision')
		expect(id).toHaveBeenCalledTimes(2)
	})
	test('rejects mismatched request, attachment, and target IDs', () => {
		const owner = new WsAttachmentBinding()
		const binding = owner.beginAttach('client', 'request', 'target')
		for (const patch of [{ requestId: 'wrong' }, { attachmentId: 'wrong' }, { targetId: 'wrong' }])
			expectViolation(owner, { ...binding, ...patch })
		expect(owner.isCurrentAttempt('client', binding)).toBe(true)
		expect(commit(owner, binding)).toMatchObject({ ok: true })
	})
	test('invalidates matching targets across clients only', () => {
		const owner = new WsAttachmentBinding()
		const shared = begin(owner, 'one', 'one', 'shared')
		commit(owner, shared)
		const pending = begin(owner, 'two', 'two', 'shared')
		const other = begin(owner, 'three', 'three', 'other')
		commit(owner, other)
		owner.invalidateTarget('shared')
		expect(owner.getCapability('one', shared.attachmentId)).toBeNull()
		expect(owner.getCapability('two', pending.attachmentId)).toBeNull()
		expect(owner.acceptsInput('one')).toBe(false)
		expect(owner.getCapability('three', other.attachmentId)).toMatchObject({ committed: true })
		expect(owner.acceptsInput('three')).toBe(true)
	})
})
